### ISSUE TITLE
analytics tracking of facet/interface interaction

### ISSUE THREAD

**Issue by phette23** [cca/libraries_branding#6]
probably want to track if

- [ ] a facet is clicked, what category of facet it is, what its value is
- [ ] if "details..." (formerly "Preview") was clicked
- [ ] clicks on best bets / database recommendations
- [ ] clicks in the right side featured pane
- [ ] clicks on upper right navigation links

**Comment by phette23** [comment]
Summon actually has pretty good built-in event tracking, we'll see if it's sufficient & if not I'll reopen this ticket.
